### PR TITLE
Update lsc file for the WLCG VO  (SOFTWARE-4331)

### PR DESCRIPTION
**Pull request by matyasselmeci**
(vomses file is already good)

### CODE REVIEW

**Comment by matyasselmeci** [comment]
OK. I downloaded the vomses and lsc files from https://wlcg-authz-wg.github.io/wlcg-authz-docs/#wlcg-vo-voms-configuration.

**Comment by brianhlin** [comment]
Andrea says the mismatch isn't intentional and that the `vomses` file should be updated to match the LSC. Though he does say that no clients care about it

**Review by brianhlin — APPROVED** [review]
LGTM

**Comment by edquist** [comment]
> The DN doesn't match between vomses and the new LSC. I was under the impression that is bad so I'm checking with Andrea

> Andrea says the mismatch isn't intentional and that the vomses file should be updated to match the LSC. Though he does say that no clients care about it

Just to note it here:

Yes the lsc file is what's actually used for the security mechanism - there are no checks in the clients that require them to be the same, but when the voms clients display a DN, as i remember it they display the one from vomses.  It made it very confusing in the past when they did not match, which was largely the motivation for the crosscheck script.  Well, it catches real mistakes, too.

Anyway, yes, they should match.

**Pull request merged**
