### PR TITLE
Remove unused CDF glidecaf settings

### PR DESCRIPTION
**Pull request by bbockelm**
Per https://ticket.opensciencegrid.org/33395

### CODE REVIEW

**Comment by steige2** [comment]
Merging this. It would be useful to know to whom the merge request was made.

**Comment by brianhlin** [comment]
@steige2 the software team's handling VO client updates now so you don't have to worry about merging these requests

**Comment by steige2** [comment]
Hello,
Yes, I know… it happened to hit my inbox at the exact time I was expecting
an update from you for the prod. mtg. agenda.

Sorry about that I’ll try to be better.
S

Scott Teige PhD
Grid Operations Center Manager
Indiana University Research Technologies
steige@iu.edu
Office: +1 812 856 7331

**Comment by brianhlin** [comment]
No problem, now it's just one less thing you have to worry about :)

**Pull request merged**
