### PR TITLE
script for generating voms-lcmaps mapfile for manual user groups

### PR DESCRIPTION
**Pull request by edquist**
uses gums.config + gums db

### CODE REVIEW

**Comment by brianhlin** [comment]
What's the difference between "manual mapping table" and "manual user groups"?

**Comment by edquist** [comment]
there is a `MAPPING` table in the gums db which has direct (manual) DN->ACCOUNT mappings, where manual user groups are user groups of DNs, which then interact with other objects in gums to eventually get mapped to accounts.

**Comment by brianhlin** [comment]
Could you add a comment with the updated output of the script?

**Comment by edquist** [comment]
Soooo, i updated the script to add custom voms mappings to the output - but it requires the other script, `gen-voms-mapfile`, to be present also (eg, with this repo checked out), rather than reproduce the somewhat-complicated logic in this script.  If you'd rather put everything in a single script, let me know.

Example output with a custom voms mapping:

```
root@el6-gumsx ~/osg-vo-config # ./bin/manual-mapfile-from-gumsdb.py 2>/dev/null
# BANNED
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Alpha Flight 7727" 
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Dancing Zorba 4528" 
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Freddie Redonschnider 1234" 

# manual mapping table
"/DC=com/DC=example/OU=People/CN=Example User 12345" test

# mappings from manual user groups
"/DC=org/DC=doegrids/OU=People/CN=Janet Doe 123456" osg
"/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345" osg
"/DC=com/DC=example/OU=People/CN=Example User 12345" osg
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013" osg

# custom VOMS mappings
"/osg/testgroup/Role=somerole/*" sam
```

**Comment by brianhlin** [comment]
I'm leaning towards putting it all in one script so that users only have to grab a single file rather than check out an entire repository. Also, we should add a tag once this is merged so that we can tell our users to grab it from a specific tag.

As for output:

1. I'd like to see more explicit instructions. For example, instead of `# custom VO mappings`

        # Add the following contents to /etc/grid-security/voms-mapfile
        # http://opensciencegrid.github.io/docs/security/lcmaps-voms-authentication/#mapping-vos
1. Let's combine the manual mapping table and the manual user groups into a single section

**Comment by edquist** [comment]
> ~I'm leaning towards putting it all in one script so that users only have to grab a single file rather than check out an entire repository.~ Actually, let's keep them separate.

Woops, already combined it into a single script.

New output:

```
# Add the following contents to /etc/grid-security/ban-mapfile
# http://opensciencegrid.github.io/docs/security/lcmaps-voms-authentication/#banning-users

"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Alpha Flight 7727" 
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Dancing Zorba 4528" 
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Freddie Redonschnider 1234" 

# ---

# Add the following contents to /etc/grid-security/grid-mapfile
# http://opensciencegrid.github.io/docs/security/lcmaps-voms-authentication/#mapping-users

"/DC=com/DC=example/OU=People/CN=Example User 12345" test
"/DC=org/DC=doegrids/OU=People/CN=Janet Doe 123456" osg
"/DC=org/DC=doegrids/OU=People/CN=Jane Doe 12345" osg
"/DC=com/DC=example/OU=People/CN=Example User 12345" osg
"/DC=org/DC=opensciencegrid/O=Open Science Grid/OU=People/CN=Carl Edquist 1013" osg

# ---

# Add the following contents to /etc/grid-security/voms-mapfile
# http://opensciencegrid.github.io/docs/security/lcmaps-voms-authentication/#mapping-vos

"/osg/testgroup/Role=somerole/*" sam

# ---

```

**Comment by edquist** [comment]
I tagged this `mapfile-generator-0.1`.

Raw download link:

https://raw.githubusercontent.com/opensciencegrid/osg-vo-config/mapfile-generator-0.1/bin/manual-mapfile-from-gumsdb.py

(although in theory getting it from `master` would be fine also.)

**Pull request merged**
