### PR TITLE
Adding the Kagra VOMS

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Comment by brianhlin** [comment]
@efajardo are you going to make an accompanying PR to topology?

**Comment by efajardo** [comment]
@brianhlin  Do I need to? It is not that the KAGRA VO will run in OSG we jsut need to create VO credentials for IGWN to run in KAGRA. The same way we do not have VIRGO in topology

**Comment by brianhlin** [comment]
Ah ok, then probably not, especially if they don't have their own area in CVMFS.

For my own edification: if they're not running in the OSG, why do we need to add their VO info to the OSG `vo-client` package? I'm not sure I understand:

> need to create VO credentials for IGWN to run in KAGRA

For IGWN to verify KAGRA services? I'm just used to the site validating incoming VOMS credentials of the client, not the other way around.

**Comment by efajardo** [comment]
So I can run `voms-proxy-init -voms kagra`

**Review by brianhlin — APPROVED** [review]
LGTM

**Pull request merged**
