### PR TITLE
Adding entry for sPHENIX VOMS.

### PR DESCRIPTION
**Pull request by jhover**

### CODE REVIEW

**Comment by brianhlin** [comment]
Hi @jhover, we'll also need updates to [vomses](https://github.com/opensciencegrid/osg-vo-config/blob/master/vomses) and [voms-mapfile-default](https://github.com/opensciencegrid/osg-vo-config/blob/master/voms-mapfile-default):

https://github.com/opensciencegrid/osg-vo-config#files-included

**Comment by jhover** [comment]
Hi Brian,

sPhenix will not be running a VOMS server, so I didn't think vomses
would be needed.

I assume for GWMS all that would be needed in the mapfile is this:

   "/sphenix/*" sphenix

... or whatever "fake VOMS ACs" the Front End factory generates for glideins

Please advise..

-john

**Comment by brianhlin** [comment]
Hey John,

Even if they're not running a VOMS server, I believe they'll need a vomses entry because the VOMS libraries will consult it when validating VOMS attributes signed by that VO. For that reason, the OSG, GLOW, and HCC VOs have vomses entries even though they don't run a VOMS server.

I could submit a PR against your repo with the necessary changes if you'd like.

\- Brian

**Comment by jhover** [comment]
That would be great, if you don't mind.

The fake VOMS server hostname is hcvoms.sdcc.bnl.gov

--john

**Pull request closed without merging**
